#@ load("@ytt:overlay", "overlay")
#@overlay/match by=overlay.subset({"apiVersion":"serving.knative.dev/v1", "kind":"Service"})
---
spec:
  template:
    spec:
      containers:
      #@overlay/match by="name"
      - name: workload
        ports:
        - name: management
          containerPort: 8081
          protocol: TCP
